### ISSUE TITLE
deviations of the results MATPOWER vs. pandapower

### ISSUE THREAD

**Issue by rbolgaryn** [G-PST/power-flow-exercise#12]
At the moment, the bus voltage deviations are too high:

       diff_vm_pu  diff_va_degree
count   70.000000       70.000000
mean     0.000962       -0.710658
std      0.022625        5.113004
min     -0.056051      -11.158032
25%     -0.006352       -3.670201
50%      0.000000       -0.705880
75%      0.008240        2.493118
max      0.063200        9.558147

**Comment by rbolgaryn** [comment]
@claytonpbarrows @kdheepak 

can you please run the load flow calculation with the latest version of the matpower grid and update the result csv files in the repo?

**Comment by claytonpbarrows** [comment]
I see no changes in the load flow results when rerunning.

**Comment by rbolgaryn** [comment]
thank you!

**Comment by rbolgaryn** [comment]
RTS grid is now verified

Bus voltages:

![grafik](https://user-images.githubusercontent.com/28706693/151991593-1e3757c3-0c02-4e94-912e-75036a9e96fd.png)

Line power injections:

![grafik](https://user-images.githubusercontent.com/28706693/151991633-ea6f8ca7-e27f-4ebc-9172-2dee941fe947.png)

Transformer power injections (HV):

![grafik](https://user-images.githubusercontent.com/28706693/151991654-a4eaa554-d25e-4b16-a9bf-6db6d2f36ffa.png)

**Comment by rbolgaryn** [comment]
As for the pegase grid it is still work in progress.

I could reproduce the bus voltages by using the pandapower grid model:

```python
net = pp.networks.case9241pegase()
```

Bus voltages:

![grafik](https://user-images.githubusercontent.com/28706693/151992030-02dfad59-19d7-4332-a703-72ed6571d95c.png)

Converting the grid from the mat file seems to have some troubles.
