### ISSUE TITLE
Rename generators according to carrier

### ISSUE THREAD

**Issue by claytonpbarrows** [G-PST/power-flow-exercise#16]

**Comment by rbolgaryn** [comment]
todo: import the extra variables from the MATPOWER file and add them to the net tables bus and gen/sgen

**Comment by rbolgaryn** [comment]
Added loading the additional data from mpc to the pandapower net:

https://github.com/e2nIEE/pandapower/pull/1464

Will be available once the PR is merged.

**Comment by rbolgaryn** [comment]
Merged in pandapower develop

**Comment by rbolgaryn** [comment]
If you also need the third column, with the source names, let me know.

**Comment by pz-max** [comment]
> If you also need the third column, with the source names, let me know.

Done. Thanks Roman :)
