### ISSUE TITLE
RTS has nonzero tap setting for last line in branch matrix

### ISSUE THREAD

**Issue by claytonpbarrows** [G-PST/power-flow-exercise#20]

**Comment by claytonpbarrows** [comment]
d5962d2c564f0a9d972e0f39d2326082eca2e165 should close

@rbolgaryn  please confirm

**Comment by rbolgaryn** [comment]
@claytonpbarrows thank you, that should be it.

Please also update the .mat file

**Comment by claytonpbarrows** [comment]
updated .mat file
